sonata_media:
    db_driver:  orm
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        sonata.media.cdn.server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        sonata.media.adapter.filesystem.local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        sonata.media.provider.file:
            resizer:    false


doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~