sonata_news:
    title:        Sonata Project
    link:         http://sonata-project.org
    description:  Rich Symfony2 bundle's


doctrine:
    orm:
        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~